# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec31a4597db3138558585fe0580f165b0541590166df38c7aa59332f2f862fbb7a88b9c72de97c1858e8bf490bc13e405593e5652a873215571230db8bb416fc

test:
  secret_key_base: bbade0399e11a252d665c5c08c69e467efc6ba31e5a8b5732c3d8686042aa57bdaa74489bd02abcac91804c6063ac73af8b29107c1589c410c7fd112c48fbc20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
